using System.Globalization;

namespace Optimizer_Windows.Localization;

public static class AppText
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["AppTitle"] = "Optimizer Windows",
        ["NavOverview"] = "Overview",
        ["NavHardware"] = "Hardware",
        ["NavOptimize"] = "Optimize",
        ["NavAbout"] = "About",
        ["Refresh"] = "Refresh",
        ["OverviewTitle"] = "System Overview",
        ["OverviewSubtitle"] = "WinUI 3 desktop shell for Windows optimization, health checks, and hardware inspection.",
        ["OverviewDevice"] = "Device",
        ["OverviewWindows"] = "Windows",
        ["OverviewProcessor"] = "Processor",
        ["OverviewMemory"] = "Memory",
        ["OverviewStorage"] = "Storage",
        ["OverviewFocus"] = "Focus",
        ["OverviewFocusTitle"] = "Safe maintenance first",
        ["OverviewFocusBody"] = "This build opens trusted Windows tools and shows live health data. No destructive one-click cleaning in v1.",
        ["OverviewDriveHealth"] = "Drive Health",
        ["HardwareSubtitle"] = "Live inventory from Windows device APIs and WMI.",
        ["HardwareCpu"] = "CPU",
        ["HardwareGpu"] = "GPU",
        ["HardwareMemory"] = "Memory",
        ["HardwareStorage"] = "Storage",
        ["HardwareNetwork"] = "Network",
        ["OptimizeSubtitle"] = "Safe shortcuts into trusted Windows maintenance surfaces.",
        ["OptimizeTempTitle"] = "Temp Folder Snapshot",
        ["OptimizeFiles"] = "Files",
        ["OptimizeSize"] = "Estimated size",
        ["OptimizeOpenTemp"] = "Open Temp Folder",
        ["OptimizeStorageSenseTitle"] = "Storage Sense",
        ["OptimizeStorageSenseBody"] = "Tune automatic cleanup policy and storage recommendations.",
        ["OptimizeStorageSenseAction"] = "Open Storage Sense",
        ["OptimizeStartupTitle"] = "Startup Apps",
        ["OptimizeStartupBody"] = "Review boot-time impact and disable heavy startup entries.",
        ["OptimizeStartupAction"] = "Open Startup Apps",
        ["OptimizeTaskManagerTitle"] = "Task Manager",
        ["OptimizeTaskManagerBody"] = "Inspect live process pressure and memory / CPU spikes.",
        ["OptimizeTaskManagerAction"] = "Open Task Manager",
        ["OptimizeDiskCleanupTitle"] = "Disk Cleanup",
        ["OptimizeDiskCleanupBody"] = "Launch native cleanup wizard instead of running silent deletes.",
        ["OptimizeDiskCleanupAction"] = "Open Disk Cleanup",
        ["OptimizeWindowsUpdateTitle"] = "Windows Update",
        ["OptimizeWindowsUpdateBody"] = "Check pending updates, driver rollups, and reboot requirements.",
        ["OptimizeWindowsUpdateAction"] = "Open Windows Update",
        ["OptimizePowerTitle"] = "Power Settings",
        ["OptimizePowerBody"] = "Switch thermal / battery behavior with native power surfaces.",
        ["OptimizePowerAction"] = "Open Power Settings",
        ["AboutIntro1"] = "Windows-only utility shell built with WinUI 3 and latest stable Windows App SDK.",
        ["AboutIntro2"] = "Current scope: live device overview, hardware inspection, and safe deep links into native optimization tools.",
        ["AboutRoadmap"] = "Roadmap",
        ["AboutRoadmap1"] = "1. Smart startup-impact analyzer",
        ["AboutRoadmap2"] = "2. Disk cleanup recommendations with file-size scoring",
        ["AboutRoadmap3"] = "3. Service and scheduled-task insight panel",
        ["AboutRoadmap4"] = "4. Exportable hardware report for troubleshooting",
        ["CommonUnknown"] = "Unknown",
        ["CommonUnavailable"] = "Unavailable",
        ["StatusLastBoot"] = "Last boot: {0}",
        ["StorageNoFixedDrives"] = "No fixed drives detected",
        ["NetworkNoActiveAdapter"] = "No active adapter",
        ["StorageAcrossDrives"] = "{0} used / {1} total across {2} drive(s)",
        ["StatusCollectingTelemetry"] = "Collecting system telemetry...",
        ["StatusCollectingHardware"] = "Collecting hardware inventory...",
        ["StatusScanningTemp"] = "Scanning temp folder...",
        ["StatusUpdated"] = "Updated {0}",
        ["StatusLoadFailed"] = "Load failed: {0}",
        ["StatusScanFailed"] = "Scan failed: {0}",
        ["StatusOpened"] = "Opened {0}",
        ["StatusOpenFailed"] = "Open failed: {0}"
    };

    private static readonly IReadOnlyDictionary<string, string> ZhHans = new Dictionary<string, string>
    {
        ["AppTitle"] = "Optimizer Windows",
        ["NavOverview"] = "概览",
        ["NavHardware"] = "硬件",
        ["NavOptimize"] = "优化",
        ["NavAbout"] = "关于",
        ["Refresh"] = "刷新",
        ["OverviewTitle"] = "系统概览",
        ["OverviewSubtitle"] = "基于 WinUI 3 的 Windows 优化与硬件信息桌面应用外壳。",
        ["OverviewDevice"] = "设备",
        ["OverviewWindows"] = "系统",
        ["OverviewProcessor"] = "处理器",
        ["OverviewMemory"] = "内存",
        ["OverviewStorage"] = "存储",
        ["OverviewFocus"] = "策略",
        ["OverviewFocusTitle"] = "先做安全维护",
        ["OverviewFocusBody"] = "当前版本优先打开系统原生工具并展示实时状态，不提供高风险一键清理。",
        ["OverviewDriveHealth"] = "磁盘健康",
        ["HardwareSubtitle"] = "通过 Windows 设备 API 与 WMI 实时采集硬件清单。",
        ["HardwareCpu"] = "处理器",
        ["HardwareGpu"] = "显卡",
        ["HardwareMemory"] = "内存",
        ["HardwareStorage"] = "存储",
        ["HardwareNetwork"] = "网络",
        ["OptimizeSubtitle"] = "以安全入口方式接入 Windows 原生优化面板。",
        ["OptimizeTempTitle"] = "临时目录快照",
        ["OptimizeFiles"] = "文件数",
        ["OptimizeSize"] = "估算体积",
        ["OptimizeOpenTemp"] = "打开临时目录",
        ["OptimizeStorageSenseTitle"] = "存储感知",
        ["OptimizeStorageSenseBody"] = "调整自动清理策略，查看系统给出的存储建议。",
        ["OptimizeStorageSenseAction"] = "打开存储感知",
        ["OptimizeStartupTitle"] = "启动应用",
        ["OptimizeStartupBody"] = "检查启动影响，关闭拖慢开机的项目。",
        ["OptimizeStartupAction"] = "打开启动应用",
        ["OptimizeTaskManagerTitle"] = "任务管理器",
        ["OptimizeTaskManagerBody"] = "定位 CPU、内存与后台进程压力来源。",
        ["OptimizeTaskManagerAction"] = "打开任务管理器",
        ["OptimizeDiskCleanupTitle"] = "磁盘清理",
        ["OptimizeDiskCleanupBody"] = "打开系统原生清理向导，而不是静默删除文件。",
        ["OptimizeDiskCleanupAction"] = "打开磁盘清理",
        ["OptimizeWindowsUpdateTitle"] = "Windows 更新",
        ["OptimizeWindowsUpdateBody"] = "检查补丁、驱动更新与重启要求。",
        ["OptimizeWindowsUpdateAction"] = "打开 Windows 更新",
        ["OptimizePowerTitle"] = "电源设置",
        ["OptimizePowerBody"] = "调整性能、续航与发热相关的系统电源行为。",
        ["OptimizePowerAction"] = "打开电源设置",
        ["AboutIntro1"] = "面向 Windows 的优化与硬件信息工具，使用 WinUI 3 与最新稳定 Windows App SDK 构建。",
        ["AboutIntro2"] = "当前聚焦系统概览、硬件清单，以及通往系统原生优化工具的安全入口。",
        ["AboutRoadmap"] = "路线图",
        ["AboutRoadmap1"] = "1. 启动项影响分析",
        ["AboutRoadmap2"] = "2. 基于文件体积评分的清理建议",
        ["AboutRoadmap3"] = "3. 服务与计划任务洞察面板",
        ["AboutRoadmap4"] = "4. 可导出的硬件诊断报告",
        ["CommonUnknown"] = "未知",
        ["CommonUnavailable"] = "不可用",
        ["StatusLastBoot"] = "上次启动：{0}",
        ["StorageNoFixedDrives"] = "未检测到固定磁盘",
        ["NetworkNoActiveAdapter"] = "没有活动网卡",
        ["StorageAcrossDrives"] = "共 {2} 个磁盘，已用 {0} / 总计 {1}",
        ["StatusCollectingTelemetry"] = "正在采集系统信息...",
        ["StatusCollectingHardware"] = "正在采集硬件清单...",
        ["StatusScanningTemp"] = "正在扫描临时目录...",
        ["StatusUpdated"] = "已更新 {0}",
        ["StatusLoadFailed"] = "加载失败：{0}",
        ["StatusScanFailed"] = "扫描失败：{0}",
        ["StatusOpened"] = "已打开 {0}",
        ["StatusOpenFailed"] = "打开失败：{0}"
    };

    public static string Get(string key)
    {
        var dictionary = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? ZhHans
            : En;

        return dictionary.TryGetValue(key, out var value) ? value : key;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(Get(key), args);
    }
}
