using System.Globalization;

namespace Optimizer_Windows.Localization;

public static class AppText
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        ["AppTitle"] = "Optimizer233-Windows",
        ["NavOverview"] = "Overview",
        ["NavHardware"] = "Hardware",
        ["NavOptimize"] = "Optimize",
        ["NavAbout"] = "About",
        ["Refresh"] = "Refresh",
        ["OverviewTitle"] = "System Overview",
        ["OverviewHeroEyebrow"] = "SYSTEM STATUS",
        ["OverviewStatusChip"] = "LIVE TELEMETRY",
        ["OverviewQuickStatus"] = "Quick Status",
        ["OverviewSubtitle"] = "WinUI 3 desktop shell for Windows optimization, health checks, and hardware inspection.",
        ["OverviewDevice"] = "Device",
        ["OverviewWindows"] = "Windows",
        ["OverviewProcessor"] = "Processor",
        ["OverviewMemory"] = "Memory",
        ["OverviewStorage"] = "Storage",
        ["OverviewFocus"] = "Focus",
        ["OverviewFocusTitle"] = "Safe maintenance first",
        ["OverviewFocusBody"] = "This build opens trusted Windows tools and shows live health data. No destructive one-click cleaning in v1.",
        ["OverviewDriveHealth"] = "Drive Health",
        ["HardwareSubtitle"] = "Live inventory from Windows device APIs and WMI.",
        ["HardwareHeroEyebrow"] = "HARDWARE MAP",
        ["HardwarePanelTitle"] = "Scan Status",
        ["HardwareInventoryTitle"] = "Detailed Inventory",
        ["HardwareCpu"] = "CPU",
        ["HardwareGpu"] = "GPU",
        ["HardwareMemory"] = "Memory",
        ["HardwareStorage"] = "Storage",
        ["HardwareNetwork"] = "Network",
        ["OptimizeSubtitle"] = "Safe shortcuts into trusted Windows maintenance surfaces.",
        ["OptimizeHeroEyebrow"] = "TACTICAL CONTROL",
        ["OptimizeHeroTitle"] = "Dark ops control center for Windows 11",
        ["OptimizeHeroBody"] = "Inspired by sharper optimizer layouts, rebuilt as a safer WinUI 3 command deck with presets, explanations, and native-tool launch flows.",
        ["OptimizeProfilesTitle"] = "Presets",
        ["OptimizeProfilesSubtitle"] = "Borrowing ZyperWin++ clarity: grouped choices first, actions second.",
        ["OptimizePresetBalancedTitle"] = "Balanced Tune",
        ["OptimizePresetBalancedBody"] = "Storage cleanup, startup inspection, and update review.",
        ["OptimizePresetBalancedAction"] = "Select Balanced",
        ["OptimizePresetStorageTitle"] = "Storage Sweep",
        ["OptimizePresetStorageBody"] = "Temp folder review, Storage Sense, and native cleanup surfaces.",
        ["OptimizePresetStorageAction"] = "Select Storage",
        ["OptimizePresetStartupTitle"] = "Boot Focus",
        ["OptimizePresetStartupBody"] = "Startup apps, task pressure, and power behavior tuning.",
        ["OptimizePresetStartupAction"] = "Select Boot",
        ["OptimizePresetNameBalanced"] = "Balanced Tune",
        ["OptimizePresetNameStorage"] = "Storage Sweep",
        ["OptimizePresetNameStartup"] = "Boot Focus",
        ["OptimizeChecklistTitle"] = "Optimization Checklist",
        ["OptimizeChecklistSubtitle"] = "Each entry is explained before launch. No silent destructive actions.",
        ["OptimizeSelectAll"] = "Select All",
        ["OptimizeClearSelection"] = "Clear",
        ["OptimizeOpenSelected"] = "Open Selected",
        ["OptimizeExportPlan"] = "Export Plan",
        ["OptimizeBadgeSafe"] = "SAFE",
        ["OptimizeTempTitle"] = "Temp Folder Snapshot",
        ["OptimizeFiles"] = "Files",
        ["OptimizeSize"] = "Estimated size",
        ["OptimizeOpenTemp"] = "Open Temp Folder",
        ["OptimizeOptionTempTitle"] = "Temp Folder",
        ["OptimizeOptionTempBody"] = "Open current user temp directory for manual review before deletion.",
        ["OptimizeStorageSenseTitle"] = "Storage Sense",
        ["OptimizeStorageSenseBody"] = "Tune automatic cleanup policy and storage recommendations.",
        ["OptimizeStorageSenseAction"] = "Open Storage Sense",
        ["OptimizeStartupTitle"] = "Startup Apps",
        ["OptimizeStartupBody"] = "Review boot-time impact and disable heavy startup entries.",
        ["OptimizeStartupAction"] = "Open Startup Apps",
        ["OptimizeTaskManagerTitle"] = "Task Manager",
        ["OptimizeTaskManagerBody"] = "Inspect live process pressure and memory / CPU spikes.",
        ["OptimizeTaskManagerAction"] = "Open Task Manager",
        ["OptimizeDiskCleanupTitle"] = "Disk Cleanup",
        ["OptimizeDiskCleanupBody"] = "Launch native cleanup wizard instead of running silent deletes.",
        ["OptimizeDiskCleanupAction"] = "Open Disk Cleanup",
        ["OptimizeWindowsUpdateTitle"] = "Windows Update",
        ["OptimizeWindowsUpdateBody"] = "Check pending updates, driver rollups, and reboot requirements.",
        ["OptimizeWindowsUpdateAction"] = "Open Windows Update",
        ["OptimizePowerTitle"] = "Power Settings",
        ["OptimizePowerBody"] = "Switch thermal / battery behavior with native power surfaces.",
        ["OptimizePowerAction"] = "Open Power Settings",
        ["AboutIntro1"] = "Windows-only utility shell built with WinUI 3 and latest stable Windows App SDK.",
        ["AboutIntro2"] = "Current scope: live device overview, hardware inspection, and safe deep links into native optimization tools.",
        ["AboutHeroEyebrow"] = "PROJECT DOSSIER",
        ["AboutRoadmap"] = "Roadmap",
        ["AboutRoadmap1"] = "1. Smart startup-impact analyzer",
        ["AboutRoadmap2"] = "2. Disk cleanup recommendations with file-size scoring",
        ["AboutRoadmap3"] = "3. Service and scheduled-task insight panel",
        ["AboutRoadmap4"] = "4. Exportable hardware report for troubleshooting",
        ["AboutPlatformTitle"] = "Platform",
        ["AboutPlatform1"] = "Win11 only",
        ["AboutPlatform2"] = "WinUI 3 + Windows App SDK 2.2.0",
        ["AboutPlatform3"] = "Binary release + GitHub Pages docs",
        ["CommonUnknown"] = "Unknown",
        ["CommonUnavailable"] = "Unavailable",
        ["StatusLastBoot"] = "Last boot: {0}",
        ["StorageNoFixedDrives"] = "No fixed drives detected",
        ["NetworkNoActiveAdapter"] = "No active adapter",
        ["StorageAcrossDrives"] = "{0} used / {1} total across {2} drive(s)",
        ["StatusCollectingTelemetry"] = "Collecting system telemetry...",
        ["StatusCollectingHardware"] = "Collecting hardware inventory...",
        ["StatusScanningTemp"] = "Scanning temp folder...",
        ["StatusUpdated"] = "Updated {0}",
        ["StatusPresetApplied"] = "Preset loaded: {0}",
        ["StatusNoSelection"] = "No items selected.",
        ["StatusOpenedSelection"] = "Opened {0} selected item(s).",
        ["StatusPlanExported"] = "Plan exported: {0}",
        ["StatusLoadFailed"] = "Load failed: {0}",
        ["StatusScanFailed"] = "Scan failed: {0}",
        ["StatusOpened"] = "Opened {0}",
        ["StatusOpenFailed"] = "Open failed: {0}"
    };

    private static readonly IReadOnlyDictionary<string, string> ZhHans = new Dictionary<string, string>
    {
        ["AppTitle"] = "Optimizer233-Windows",
        ["NavOverview"] = "概览",
        ["NavHardware"] = "硬件",
        ["NavOptimize"] = "优化",
        ["NavAbout"] = "关于",
        ["Refresh"] = "刷新",
        ["OverviewTitle"] = "系统概览",
        ["OverviewHeroEyebrow"] = "系统态势",
        ["OverviewStatusChip"] = "实时遥测",
        ["OverviewQuickStatus"] = "快速状态",
        ["OverviewSubtitle"] = "基于 WinUI 3 的 Windows 优化与硬件信息桌面应用外壳。",
        ["OverviewDevice"] = "设备",
        ["OverviewWindows"] = "系统",
        ["OverviewProcessor"] = "处理器",
        ["OverviewMemory"] = "内存",
        ["OverviewStorage"] = "存储",
        ["OverviewFocus"] = "策略",
        ["OverviewFocusTitle"] = "先做安全维护",
        ["OverviewFocusBody"] = "当前版本优先打开系统原生工具并展示实时状态，不提供高风险一键清理。",
        ["OverviewDriveHealth"] = "磁盘健康",
        ["HardwareSubtitle"] = "通过 Windows 设备 API 与 WMI 实时采集硬件清单。",
        ["HardwareHeroEyebrow"] = "硬件拓扑",
        ["HardwarePanelTitle"] = "扫描状态",
        ["HardwareInventoryTitle"] = "详细清单",
        ["HardwareCpu"] = "处理器",
        ["HardwareGpu"] = "显卡",
        ["HardwareMemory"] = "内存",
        ["HardwareStorage"] = "存储",
        ["HardwareNetwork"] = "网络",
        ["OptimizeSubtitle"] = "以安全入口方式接入 Windows 原生优化面板。",
        ["OptimizeHeroEyebrow"] = "战术控制台",
        ["OptimizeHeroTitle"] = "面向 Windows 11 的黑暗作战中控台",
        ["OptimizeHeroBody"] = "参考 ZyperWin++ 的清晰分组逻辑，但重做为更安全、更现代的 WinUI 3 指挥台：先选预设，再看说明，再打开系统原生工具。",
        ["OptimizeProfilesTitle"] = "预设方案",
        ["OptimizeProfilesSubtitle"] = "借鉴 ZyperWin++ 的信息结构：先分组，再执行。",
        ["OptimizePresetBalancedTitle"] = "均衡调优",
        ["OptimizePresetBalancedBody"] = "覆盖存储清理、启动项检查和更新复核。",
        ["OptimizePresetBalancedAction"] = "选择均衡",
        ["OptimizePresetStorageTitle"] = "存储清扫",
        ["OptimizePresetStorageBody"] = "聚焦临时目录、存储感知和系统原生清理入口。",
        ["OptimizePresetStorageAction"] = "选择存储",
        ["OptimizePresetStartupTitle"] = "启动加速",
        ["OptimizePresetStartupBody"] = "聚焦启动应用、任务压力和电源行为。",
        ["OptimizePresetStartupAction"] = "选择启动",
        ["OptimizePresetNameBalanced"] = "均衡调优",
        ["OptimizePresetNameStorage"] = "存储清扫",
        ["OptimizePresetNameStartup"] = "启动加速",
        ["OptimizeChecklistTitle"] = "优化清单",
        ["OptimizeChecklistSubtitle"] = "每个条目先说明再执行，不做静默破坏性操作。",
        ["OptimizeSelectAll"] = "全选",
        ["OptimizeClearSelection"] = "清空",
        ["OptimizeOpenSelected"] = "打开所选",
        ["OptimizeExportPlan"] = "导出方案",
        ["OptimizeBadgeSafe"] = "安全",
        ["OptimizeTempTitle"] = "临时目录快照",
        ["OptimizeFiles"] = "文件数",
        ["OptimizeSize"] = "估算体积",
        ["OptimizeOpenTemp"] = "打开临时目录",
        ["OptimizeOptionTempTitle"] = "临时目录",
        ["OptimizeOptionTempBody"] = "先打开当前用户临时目录，人工确认后再决定删除内容。",
        ["OptimizeStorageSenseTitle"] = "存储感知",
        ["OptimizeStorageSenseBody"] = "调整自动清理策略，查看系统给出的存储建议。",
        ["OptimizeStorageSenseAction"] = "打开存储感知",
        ["OptimizeStartupTitle"] = "启动应用",
        ["OptimizeStartupBody"] = "检查启动影响，关闭拖慢开机的项目。",
        ["OptimizeStartupAction"] = "打开启动应用",
        ["OptimizeTaskManagerTitle"] = "任务管理器",
        ["OptimizeTaskManagerBody"] = "定位 CPU、内存与后台进程压力来源。",
        ["OptimizeTaskManagerAction"] = "打开任务管理器",
        ["OptimizeDiskCleanupTitle"] = "磁盘清理",
        ["OptimizeDiskCleanupBody"] = "打开系统原生清理向导，而不是静默删除文件。",
        ["OptimizeDiskCleanupAction"] = "打开磁盘清理",
        ["OptimizeWindowsUpdateTitle"] = "Windows 更新",
        ["OptimizeWindowsUpdateBody"] = "检查补丁、驱动更新与重启要求。",
        ["OptimizeWindowsUpdateAction"] = "打开 Windows 更新",
        ["OptimizePowerTitle"] = "电源设置",
        ["OptimizePowerBody"] = "调整性能、续航与发热相关的系统电源行为。",
        ["OptimizePowerAction"] = "打开电源设置",
        ["AboutIntro1"] = "面向 Windows 的优化与硬件信息工具，使用 WinUI 3 与最新稳定 Windows App SDK 构建。",
        ["AboutIntro2"] = "当前聚焦系统概览、硬件清单，以及通往系统原生优化工具的安全入口。",
        ["AboutHeroEyebrow"] = "项目档案",
        ["AboutRoadmap"] = "路线图",
        ["AboutRoadmap1"] = "1. 启动项影响分析",
        ["AboutRoadmap2"] = "2. 基于文件体积评分的清理建议",
        ["AboutRoadmap3"] = "3. 服务与计划任务洞察面板",
        ["AboutRoadmap4"] = "4. 可导出的硬件诊断报告",
        ["AboutPlatformTitle"] = "平台基线",
        ["AboutPlatform1"] = "仅支持 Win11",
        ["AboutPlatform2"] = "WinUI 3 + Windows App SDK 2.2.0",
        ["AboutPlatform3"] = "二进制发布 + GitHub Pages 文档",
        ["CommonUnknown"] = "未知",
        ["CommonUnavailable"] = "不可用",
        ["StatusLastBoot"] = "上次启动：{0}",
        ["StorageNoFixedDrives"] = "未检测到固定磁盘",
        ["NetworkNoActiveAdapter"] = "没有活动网卡",
        ["StorageAcrossDrives"] = "共 {2} 个磁盘，已用 {0} / 总计 {1}",
        ["StatusCollectingTelemetry"] = "正在采集系统信息...",
        ["StatusCollectingHardware"] = "正在采集硬件清单...",
        ["StatusScanningTemp"] = "正在扫描临时目录...",
        ["StatusUpdated"] = "已更新 {0}",
        ["StatusPresetApplied"] = "已加载预设：{0}",
        ["StatusNoSelection"] = "当前没有选中项目。",
        ["StatusOpenedSelection"] = "已打开 {0} 个所选项目。",
        ["StatusPlanExported"] = "方案已导出：{0}",
        ["StatusLoadFailed"] = "加载失败：{0}",
        ["StatusScanFailed"] = "扫描失败：{0}",
        ["StatusOpened"] = "已打开 {0}",
        ["StatusOpenFailed"] = "打开失败：{0}"
    };

    public static string Get(string key)
    {
        var dictionary = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? ZhHans
            : En;

        return dictionary.TryGetValue(key, out var value) ? value : key;
    }

    public static string Format(string key, params object[] args)
    {
        return string.Format(Get(key), args);
    }
}
